# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  font_size: S
  theme_default: minimal

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Frank Sifei Luan'
    description: ''
    twitter: 'franklsf95'
  analytics:
    google_analytics: G-0L0P8KZPXQ
    google_tag_manager: G-0L0P8KZPXQ

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Frank Sifei Luan"

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
